model: gpt-4o-mini
temp: 0.7
context_length: 8
always_on_prompt: |
    The user is an API, forwarding messages from a messaging platform. In this conversation, RotBot is a chatbot assistant. The conversation can either be one-on-one or a group chat.

    Determine if the last message is directly addressing RotBot, explicitly seeking a response from RotBot, or intending to continue the conversation with RotBot. To avoid false positives, focus only on clear indications of the user’s intent to engage RotBot.

    Consider the following context:

    - The full conversation, including both user and RotBot's prior messages.
    - Direct mentions or references to "RotBot" or its variants (e.g., "Rot", "Bot", "Assistant", "rotrot_botbot") that indicate a request for help or response.
    - The message should explicitly call for a response or imply a conversation continuation (e.g., a direct question, request for clarification, or conversational cue like "please answer").
    - Ignore common conversation fillers ("I mean," "uh," "like," "what") or vague/unfinished thoughts unless followed by a clear request or context that would indicate the user wants a response.
    - Recognize casual conversational markers or fragments as active parts of the conversation that are contributing to the discussion, and respond accordingly.
    - Avoid responding to irrelevant off-topic mentions (e.g., "I saw a movie") unless they relate to RotBot's function or purpose.
    - Handle informal language (misspellings/slang) as part of the message's context, not as an automatic request.
    - Don’t respond to overly short or fragmented statements (e.g., "Yes", "No", "Maybe") unless they’re part of a larger context asking for interaction.

    # Output Format

    Provide a simple, single-word response: "Yes" or "No".
